### PR TITLE
MSVC compatibility

### PR DESCRIPTION
**Pull request by jibsen**
As discussed in #8.

This should allow compiling lzfse with MSVC 2015. The CLI tool is able to compress and extract the few test files I used.

### CODE REVIEW

**Comment by ebainville** [comment]
Jørgen, I tested your changes compile and work on macOS (yes, they do).
How do I build this on a PC with VS Community 2015?
NMAKE complains about the Makefile. Maybe we could provide a Solution? (or is it still called a Solution? I didn't touch VS in the last 5 years :-)

**Comment by jibsen** [comment]
I think VS solution files can become a bit of an update nightmare for projects that are not using VS for development.

I added a commit that fixes building as a dll, so CMake can be used both to generate VS solution files and NMake makefiles. For instance, here I run:

``` .cmd
mkdir build
cd build
cmake ..
```

and then either open the generated solution in the IDE, or build it with `cmake --build . --config Release` (which calls MSBuild for MSVC).

**Comment by ebainville** [comment]
Excellent. I'll try it this evening. Thanks.

**Comment by ebainville** [comment]
OK, it works, thanks again.

**Pull request merged**
