### PR TITLE
Allow LZVN to work with inputs shorter than 8 bytes.

### PR DESCRIPTION
**Pull request by nemequ**
**Please review this carefully, I'm not particularly confident of the change.**

I'd really like to be able to expose a LZVN in [Squash](https://quixdb.github.io/squash/), but the requirement of the _input_ buffer being at least 8 bytes is a problem.  Output isn't a big deal since I can just compress to a temporary 8-byte buffer, then copy it over to the "real" output buffer if there is enough room.

After poking around the code a bit, it occurs to me that it should be possible to just skip the compression part and write the entire buffer as a literal, just like you already do for the trailing few bytes.  This patch, _I think_, does that.  I'm not very familiar with the code base, or the compression format, though, so please be careful applying this.

I've modified the Squash LZFSE plugin to also expose LZVN, and with this change it does pass [all Squash's unit tests](https://github.com/quixdb/squash/tree/master/tests), which is about all I can do.  Here is the diff for the changes to Squash in case you want to play with it:

``` diff
diff --git a/plugins/lzfse/squash-lzfse.c b/plugins/lzfse/squash-lzfse.c
index f72324f..39514e5 100644
--- a/plugins/lzfse/squash-lzfse.c
+++ b/plugins/lzfse/squash-lzfse.c
@@ -34,6 +34,8 @@

 #include "lzfse/src/lzfse.h"
 #include "lzfse/src/lzfse_internal.h"
+#include "lzfse/src/lzvn_encode_base.h"
+#include "lzfse/src/lzvn_decode_base.h"

 SQUASH_PLUGIN_EXPORT
 SquashStatus squash_plugin_init_codec (SquashCodec* codec, SquashCodecImpl* impl);
@@ -101,14 +103,101 @@ squash_lzfse_compress_buffer (SquashCodec* codec,
   return SQUASH_OK;
 }

+static size_t
+squash_lzvn_get_max_compressed_size (SquashCodec* codec, size_t uncompressed_size) {
+  return (uncompressed_size) + (uncompressed_size / 80) + 16;
+}
+
+static SquashStatus
+squash_lzvn_decompress_buffer (SquashCodec* codec,
+                               size_t* decompressed_size,
+                               uint8_t decompressed[SQUASH_ARRAY_PARAM(*decompressed_size)],
+                               size_t compressed_size,
+                               const uint8_t compressed[SQUASH_ARRAY_PARAM(compressed_size)],
+                               SquashOptions* options) {
+  lzvn_decoder_state decoder = { 0, };
+
+  decoder.src = compressed;
+  decoder.src_end = compressed + compressed_size;
+
+  decoder.dst = decompressed;
+  decoder.dst_begin = decompressed;
+  decoder.dst_end = decompressed + *decompressed_size;
+  decoder.dst_current = decompressed;
+
+  lzvn_decode (&decoder);
+
+  const size_t bytes_read = decoder.src - compressed;
+  const size_t bytes_written = decoder.dst - decoder.dst_begin;
+
+  if (SQUASH_UNLIKELY(bytes_read != compressed_size)) {
+    if (bytes_written == *decompressed_size)
+      return SQUASH_BUFFER_FULL;
+    else
+      return SQUASH_FAILED;
+  }
+
+  *decompressed_size = bytes_written;
+
+  return SQUASH_OK;
+}
+
+static SquashStatus
+squash_lzvn_compress_buffer (SquashCodec* codec,
+                             size_t* compressed_size,
+                             uint8_t compressed[SQUASH_ARRAY_PARAM(*compressed_size)],
+                             size_t uncompressed_size,
+                             const uint8_t uncompressed[SQUASH_ARRAY_PARAM(uncompressed_size)],
+                             SquashOptions* options) {
+  uint8_t outbuf[LZVN_ENCODE_MIN_DST_SIZE];
+  uint8_t* dest;
+  size_t dest_l;
+
+  if (SQUASH_UNLIKELY(*compressed_size < sizeof(outbuf))) {
+    dest = outbuf;
+    dest_l = sizeof(outbuf);
+  } else {
+    dest = compressed;
+    dest_l = *compressed_size;
+  }
+
+  void* workmem = squash_malloc (LZVN_ENCODE_WORK_SIZE);
+  if (SQUASH_UNLIKELY(workmem == NULL))
+    return squash_error (SQUASH_MEMORY);
+
+  dest_l =
+    lzvn_encode_buffer(dest, dest_l,
+                       uncompressed, uncompressed_size,
+                       workmem);
+
+  squash_free (workmem);
+
+  if (SQUASH_UNLIKELY(dest_l == 0))
+    return squash_error (SQUASH_BUFFER_FULL);
+
+  if (SQUASH_UNLIKELY(dest == outbuf)) {
+    if (*compressed_size < dest_l)
+      return squash_error (SQUASH_BUFFER_FULL);
+
+    memcpy (compressed, dest, dest_l);
+  }
+
+  *compressed_size = dest_l;
+  return SQUASH_OK;
+}
+
 SquashStatus
 squash_plugin_init_codec (SquashCodec* codec, SquashCodecImpl* impl) {
   const char* name = squash_codec_get_name (codec);

-  if (SQUASH_LIKELY(strcmp ("lzfse", name) == 0)) {
+  if (strcmp ("lzfse", name) == 0) {
     impl->get_max_compressed_size = squash_lzfse_get_max_compressed_size;
     impl->decompress_buffer = squash_lzfse_decompress_buffer;
     impl->compress_buffer = squash_lzfse_compress_buffer;
+  } else if (strcmp ("lzvn", name) == 0) {
+    impl->get_max_compressed_size = squash_lzvn_get_max_compressed_size;
+    impl->decompress_buffer = squash_lzvn_decompress_buffer;
+    impl->compress_buffer = squash_lzvn_compress_buffer;
   } else {
     return SQUASH_UNABLE_TO_LOAD;
   }
diff --git a/plugins/lzfse/squash.ini b/plugins/lzfse/squash.ini
index 11f1324..e3fcf60 100644
--- a/plugins/lzfse/squash.ini
+++ b/plugins/lzfse/squash.ini
@@ -1,3 +1,4 @@
 license=BSD3

 [lzfse]
+[lzvn]
```

### CODE REVIEW

**Comment by ebainville** [comment]
Evan, after thinking about it, I'd prefer to not take that change. Exposing LZVN isn't part of the scope of this repository. Also, the 8 B limit is not really an issue if you really want to use the LZVN internal API (as you did in Squash).

**Comment by nemequ** [comment]
> Also, the 8 B limit is not really an issue if you really want to use the LZVN internal API (as you did in Squash).

How so?  The internal limit is in `lzvn_encode_partial`, which is the function called by `lzvn_encode_buffer`, which is what I use in Squash (it's the only non-static function in the LZVN encoder, so I don't have much choice).  Without the patch I get an error when trying to compress < 8 bytes, which is a blocker for LZVN support in the plugin.

The only way I could get around this would be to basically reimplement `lzvn_encode_partial`, but that's not really possible since it uses a bunch of static symbols

If the patch is incorrect I understand, but the decoder doesn't seem to have an issue…  There is already a special case for inputs < 8 bytes, why not just make it a special case which works?

**Comment by nemequ** [comment]
BTW, a benchmark which includes LZVN is at https://quixdb.github.io/squash-benchmark/unstable/

As you can see, LZVN tends to dominate LZFSE in terms of decoding speed, though the ratio and compression speeds aren't quite as good.  I think it's every bit as interesting as LZFSE, if not more so…  LZVN has a more unique balance (across compression speed, decompression speed, and compression ratio), whereas LZFSE tends to be outclassed by zstd and libdeflate.  I'd really like to see this library expose LZVN publicly, I think it could be very useful for some people.

**Comment by ebainville** [comment]
Yes, I have seen these curves. What was the compiler/options used to generate the code?
We could take your change without changing the main header and the command line tool. That's unblocking you, but still doesn't make LZVN a first class citizen of our API.

**Comment by nemequ** [comment]
> What was the compiler/options used to generate the code?

clang-3.5.0 (Fedora 22), `-O3 -DNDEBUG`.  Once squash 0.8 is released I'll run it on a bunch of different computers and compilers (including several ARM machines, and probably one POWER8), but the optimization flags probably won't change.

That said, I do respect library developer's wishes for compiler flags, so if there is something you want me to add specifically for LZFSE I'm willing to do so, as long as it doesn't break anything.  Unfortunately LTO is one of those thing which breaks stuff.

> We could take your change without changing the main header and the command line tool.

Yes, I tried to make the change as non-intrusive as possible.  There is still a check at lzfse_encode.c:40 which avoids invoking lzvn_encode if `src_size < LZVN_ENCODE_MIN_SRC_SIZE`, so it shouldn't alter `lzfse_encode_buffer`'s behavior.  My hesitation is only in the fact that I don't fully grok what is going on at a lower level in the codec, and I don't want to cause the encoder to create invalid streams.  Basically, I saw the check that was causing problems, thought "hmm, maybe if I do this…", and it seems to have worked :).  If the patch is correct, I think it's pretty reasonable; the API remains internal, and it's usable for short inputs, but the behavior shouldn't change for anyone using the public APIs.

Long-term, I hope you'll revisit the idea of making LZVN part of the public API, but for now I don't mind using internal/unstable APIs in the Squash plugin; I just don't want to maintain a fork.

**Comment by ebainville** [comment]
About the flags, we get best results with clang -Os -march=haswell if the target machine allows it. If you run on macOS, you could also benchmark the implementation in the Compression library.
I'll validate the changes here (from the LZFSE API, not direct calls to LZVN).
Thanks.

**Comment by nemequ** [comment]
> About the flags, we get best results with clang -Os -march=haswell if the target machine allows it.

-march=haswell won't work since the default flags have to be portable, but I could do -Os… actually, it's probably not a bad idea to make that the default for all codecs.

> If you run on macOS, you could also benchmark the implementation in the Compression library.

Sorry, I don't have a Mac.  [A plugin for Apple's compression library](https://github.com/quixdb/squash/issues/146) is something I've wanted for a while, but I don't have a way to do the development, and without an OS X >= 10.11 machine available for CI ([Travis is still on 10.9](https://docs.travis-ci.com/user/osx-ci-environment/)) maintaining it would be tricky.  Of course, even with a Squash plugin for the API I would still have no way to run it.

**Pull request merged**
