### PR TITLE
Don't rely on unaligned accesses in the LZVN encoder.

### PR DESCRIPTION
**Pull request by nemequ**
This also enables an ubsan build on Travis (which didn't work before
this patch).

### CODE REVIEW

**Comment by nemequ** [comment]
Oops, looks like my whitespace setup is different; give me a minute, I'll fix it :/

**Comment by nemequ** [comment]
Fixed, sorry about the noise.

**Comment by ebainville** [comment]
I'll have a look at it. Thanks.

**Comment by ebainville** [comment]
Changes tested on macOS.
Thanks.

**Pull request merged**
