### PR TITLE
Add CMake build system.

### PR DESCRIPTION
**Pull request by nemequ**
As discussed in #15, rebased on master.  Still wondering about the answers to the questions I asked there, but this should at least be a good starting point.

FWIW, I'm willing to help with maintenance on this, just ping me if you need something.

### CODE REVIEW

**Comment by ebainville** [comment]
Thanks for your changes. Is it possible to not overwrite 'Makefile' and use something like 'Makefile.cmake'. Also, we need an automated way to remove all the generated files.

**Comment by jibsen** [comment]
With CMake you often do an [out-of-source](https://cmake.org/Wiki/CMake_FAQ#Out-of-source_build_trees) build. I.e.

``` .bash
mkdir build
cd build
cmake ..
make
```

Which means cleaning up is just removing the build folder.

**Comment by ebainville** [comment]
OK, I see. Then it works as expected. I'll also add a note in the README.

**Comment by nemequ** [comment]
Also, `git clean -xdf`.

For srcdir = builddir I don't _think_ there is a way to specify the 
makefile name, though of course you could use a different generator (e.g., 
ninja).

Is there really a need to keep the existing system?  CMake should do 
everything the current system does, but with better portability.  If you 
want, I can also add https://github.com/nemequ/configure-cmake so people 
used to autotools aren't confused...

Sent with AquaMail for Android
http://www.aqua-mail.com

**Pull request merged**
