### PR TITLE
Add CMake build system.

### PR DESCRIPTION
**Pull request by grp**
Roughly equivalent to the Makefile-based build system, but much easier to incorporate into a larger project.

### CODE REVIEW

**Comment by ebainville** [comment]
I'll review this shortly. Please can you update the change in README to the README.md I just merged. Thanks.

**Comment by grp** [comment]
Updated!

**Comment by nemequ** [comment]
None of the options are tested to see if they are actually supported by the compiler.  At best this will break MSVC (assuming the patches mentioned in #8 get merged), but possibly other compilers.
- For CMake >= 3.1, the right way to set the C standard is to set the [C_STANDARD](https://cmake.org/cmake/help/v3.1/prop_tgt/C_STANDARD.html) property.  https://github.com/quixdb/squash/blob/master/cmake/RequireStandard.cmake works with (at least) 2.8.6+
- For CMake >= 2.8.12, the right way to control visibility is the [C_VISIBILITY](https://cmake.org/cmake/help/v2.8.12/cmake.html#prop_tgt:LANG_VISIBILITY_PRESET).  I would just set the target property behind a test for the CMake version, people using ancient versions of cmake can live without it.
- For the warnings, you need to check the flag to enable the warning (see https://gcc.gnu.org/wiki/FAQ#wnowarning for why), see https://github.com/quixdb/squash/blob/master/cmake/AddCompilerFlags.cmake#L83 for an example of how do do it.  That function is a bit overkill because it needs to support mixed c/c++ targets, but it wouldn't be hard to simplify (just set the COMPILE_FLAGS target property, no need to loop though the sources).

If you want to use the liblzfse static library elsewhere you should probably [enable position independent code](https://cmake.org/cmake/help/v2.8.9/cmake.html#prop_tgt:POSITION_INDEPENDENT_CODE) (note: requires CMake 2.8.9+).  Otherwise you're likely to get an error when trying to include lzfse in a shared library.

**Comment by grp** [comment]
This is intended to exactly mirror the existing Makefile, which makes the same assumptions. My thought was that additional generalization could happen along with code-level support for additional environments, for example as part of #8 for MSVC.

I don't have access to MSVC to test the more involved changes, but another option could be to gate these behind `if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU|Clang")` for now?

**Comment by nemequ** [comment]
If you don't want to fix it up a bit, I'll probably do it soon… I'm trying to [move the plugin's build system logic out of Squash](https://github.com/quixdb/squash/issues/202) anyways.  In the meantime, you're right, it's not any worse than the makefile.

AFAIK GNU|Clang won't play nice with Intel.  There is also suncc, cray, ekopath, green hill, ibm xl, etc., plus a bunch which I don't really care about since they are too far behind in terms of optimizing.

**Comment by nemequ** [comment]
Okay, I put together a quick CMakeLists.txt: https://github.com/nemequ/lzfse/blob/master/CMakeLists.txt

I've tested it with cmake versions down to 2.8.6 (from Solaris 11), it should be pretty reliable.  I've also tested using it for the Squash plugin (by just doing `add_subdirectory(lzfse)` then linking to the `lzfse` target, which was a static library in this case).

One thing I didn't do was add version information to the library.  It's probably not a bad idea; if you want I can go ahead and add it.  If you want to install the library and header instead of expecting everyone to bundle lzfse in their project, I think periodic releases (and, therefore, version numbers) are the right way to go.  If not, IMHO I should completely remove the installation feature from this (and the same should be done for the Makefile).

I also didn't remove the existing Makefile-based build system; not sure if you want to do that or not.  FWIW, I'm not a big fan of maintaining parallel build systems for a single project, but if that's what you want to do it's not really a big deal.

On a related note, if you want to add an autotools-style wrapper for the cmake build system, I have a small script for that: https://github.com/nemequ/configure-cmake/

**Comment by ebainville** [comment]
Work rebased and merged with PR #24

**Pull request closed without merging**
